__title__ = 'jobmonitor'
__description__ = 'Job Monitor.'
__url__ = 'https://github.com/vicalloy/jobmonitor/'
__version__ = '0.9.0'
__build__ = 0x022100
__author__ = 'vicalloy'
__author_email__ = 'zbirder@gmail.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2018 vicalloy'
